openapi: 3.0.3
info:
  title: Sample API
  description: Sample API
  version: 1.0.0
servers:
  - url: https://jsonplaceholder.typicode.com/
    description: Json Placeholder API server
paths:
  /posts:
    get:
      summary: List todos
      description: Returns a list of todos
      operationId: listTodos
      parameters:
        - name: userId
          in: query
          description: Filter posts by user ID
          schema:
            type: integer

      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    userId:
                      type: integer
                      description: ID of the user who created the post
                    id:
                      type: integer
                      description: Post ID
                    title:
                      type: string
                      description: Post title
                    body:
                      type: string
                      description: Post content
